name: Flutter Plugin CI

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - develop

jobs:

  build:
    runs-on: macos-latest

    steps:
      - name: Set up Flutter
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.12'

      - name: Check out code
      - uses: actions/checkout@v3

      - name: Navigate to example directory
        run: cd example

      - name: Install dependencies
        run: flutter pub get

      - name: Run tests
        run: flutter test

      - name: Build Android app
        run: flutter build apk

      - name: Build iOS app
        run: flutter build ios --no-codesign
