name: Build Test Steps

on:
  workflow_call:

jobs: 
  build:
    runs-on: macos-latest

    steps:
      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.2'

      - name: Check out code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: flutter pub get

      - name: Lint code
        run: flutter analyze

      - name: Run tests
        run: flutter test